/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "suignxunuunxhrauukke"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1aWdueHVudXVueGhyYXV1a2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNzYxNzEsImV4cCI6MjA3Nzc1MjE3MX0.9-9D-25ToEZKwQH0y1E4SADQYXHNZr0Eg8tiial-QJM"